version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    neural_transfer:
      image: silked/deep-oc-neural_transfer
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    neural_transfer-gpu:
      image: silked/deep-oc-neural_transfer:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    neural_transfer-rclone:
      extends:
        service: neural_transfer
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
